'use client'
import { Geist, Geist_Mono } from "next/font/google";
import Provider from "./Provider";
import "./globals.css";
import { MainNavBar } from "./Components/NavBar/MainNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <MainNavBar/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
